version: '3.9'
networks:
  postgres-network:
    driver: bridge
services:
    postgresql:
        container_name: postgresql
        image: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "userapp"
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '2G'
        networks:
            - postgres-network
        restart: always
    web:
        build: .
        container_name: web
        depends_on:
            - postgresql
        ports:
            - "5000:5000"
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '1G'
        volumes:
            - .:/code
        env_file:
            - config.env
        command: python3 app.py
        networks:
            - postgres-network
        restart: always
    pgadmin4:
        image: dpage/pgadmin4
        depends_on:
          - postgresql
        environment:
            PGADMIN_DEFAULT_USER: admin
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
          - ./pgadmin:/var/lib/pgadmin
        networks:
          - postgres-network
        ports:
          - "5433:80"