"""empty message

Revision ID: 4a2e208efb53
Revises: c571b12b0dfc
Create Date: 2023-04-13 15:30:03.528977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2e208efb53'
down_revision = 'c571b12b0dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('ra',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_constraint('student_cpf_key', type_='unique')
        batch_op.drop_constraint('student_email_key', type_='unique')
        batch_op.drop_constraint('student_phone_key', type_='unique')
        batch_op.create_unique_constraint(None, ['ra'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('student_phone_key', ['phone'])
        batch_op.create_unique_constraint('student_email_key', ['email'])
        batch_op.create_unique_constraint('student_cpf_key', ['cpf'])
        batch_op.alter_column('ra',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
