"""empty message

Revision ID: 650fae9e5c8b
Revises: eeda58ab0de5
Create Date: 2023-03-28 12:54:52.253133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650fae9e5c8b'
down_revision = 'eeda58ab0de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('returned_at')

    # ### end Alembic commands ###
