"""empty message

Revision ID: f07957967ca4
Revises: 7182043cf0c8
Create Date: 2023-01-24 23:34:02.308393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f07957967ca4'
down_revision = '7182043cf0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('corporate_name', sa.String(length=80), nullable=False),
    sa.Column('fantasy_name', sa.String(length=80), nullable=False),
    sa.Column('cpnj', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('cpf_owner', sa.String(length=120), nullable=False),
    sa.Column('coordinate_x', sa.String(length=80), nullable=True),
    sa.Column('coordinate_y', sa.String(length=80), nullable=True),
    sa.Column('head_office', sa.Boolean(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpnj'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant')
    # ### end Alembic commands ###
