"""empty message

Revision ID: f12b56000fc0
Revises: 5c12c853b40c
Create Date: 2023-04-22 00:36:18.533387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12b56000fc0'
down_revision = '5c12c853b40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), autoincrement=True, nullable=True))

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), autoincrement=True, nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), autoincrement=True, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('index')

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('index')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###
